Bengal alterations
liatrio/devops-bootcamp pull request #192
Opened 2022-04-13 20:44 UTC by zjorge96

2022-05-23 17:37 UTC, ChrisSchreiber requested changes

2022-05-23 17:37 UTC, MisterC500 reviewed
Looks good! Just left one comment.

2022-05-23 17:37 UTC, MisterC500 commented on docs/2-virtual-machines-containers/2.5.2-kubernetes.md
> -Kubernetes is declarative by design. When you want to change something in the cluster, you simply create/update/delete the resources from etcd via the API server. Various controllers then respond to
Total nicpic, but isn't converging the right term here?

2022-05-23 19:13 UTC, MisterC500 approved these changes

2022-05-23 23:11 UTC, zjorge96 commented on docs/2-virtual-machines-containers/2.5.2-kubernetes.md
> +Kubernetes is declarative by design. When you want to change something in the cluster, you simply create/update/delete the resources from etcd via the API server. Various controllers then respond to
Changed converting back to converging 👍

2022-05-24 15:02 UTC, ChrisSchreiber approved these changes

2022-05-24 21:30 UTC, merged