Added quiz to 3.5.1 about Docker Compose
liatrio/devops-bootcamp pull request #436
Opened 2024-01-12 22:20 UTC by cfculler

Tests basic understanding of how Docker Compose aids you in managing containers

2024-01-16 18:30 UTC, jburns24 requested changes
Please remove scalability as an advantage of Compose (or argue to me that it is an advantage)

2024-01-16 22:19 UTC, cfculler commented on src/quizzes/chapter-3/3.5.1/docker-compose-quiz.js
> +	> Good. You can easily define or change the number of replicas of containers, which will scale up or down the container count and split work among them
Got it, I mistakenly thought Compose came OOTB with a `replicas` field that would spin up more containers, and then that thought was confirmed by my arch nemesis (ChatGPT 3.5). I just did more research and had the same findings as you. I'll make an adjustment to the question

2024-01-16 22:30 UTC, cfculler commented on src/quizzes/chapter-3/3.5.1/docker-compose-quiz.js
> +	> Good. You can easily define or change the number of replicas of containers, which will scale up or down the container count and split work among them
The answer option is still there, but it is incorrect now. I rewrote the feedback for it to A) highlight a downside of Docker Compose and B) act as a Segway into Kubernetes

2024-01-18 00:11 UTC, jburns24 approved these changes

2024-01-18 00:12 UTC, merged